general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

# time
label {
    text = cmd[update:1000] date +"%H:%M:%S"
    color = rgb(cdd6f4)
    font_size = 80
    font_family = NotoSans Nerd Font
    position = 0, 200
}

# date
label {
    text = cmd[update:60000] date +"%A, %B %d, %Y"
    color = rgb(cdd6f4)
    font_size = 24
    font_family = NotoSans Nerd Font
    position = 0, 120
}

# password input
input-field {
    size = 400, 60
    outline_thickness = 3
    dots_spacing = 0.25
    outer_color = rgb(cba6f7)
    inner_color = rgba(30304488)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 10
    check_color = rgb(89b4fa)
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = rgb(f9e2af)
}
