#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# swallow terminals that are busy running other apps
pgrep bspswallow || bspswallow &

# remove external monitor after it is disconnected
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# general settings
bspc config border_width         1
bspc config window_gap          20
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# Floating
bspc rule -a alsamixer state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Steam state=floating
bspc rule -a Zathura state=tiled

# Open applications on specific workspaces
bspc rule -a firefox desktop='^1'
bspc rule -a Steam desktop='^7'
bspc rule -a discord desktop='^9'

# startup
autorandr -c & # laptop only
# /home/sisoro/.config/bspwm/screenlayout.sh & # desktop only
# nvidia-settings -a DigitalVibrance=300 & # desktop only
./.fehbg &
picom --config /home/sisoro/.config/picom/picom.conf &
bluetoothctl power on &
nm-applet &
# /home/sisoro/.config/bspwm/monitor-control.sh # laptop only
~/.config/polybar/launch.sh &

