#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d I II III IV V VI VII VIII IX X

# general settings
bspc config border_width         1
bspc config window_gap          20
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Floating
bspc rule -a alsamixer state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Steam state=floating
bspc rule -a UnityHub state=floating

# Open applications on specific workspaces
bspc rule -a firefox desktop='^1'
bspc rule -a Steam desktop='^7'
bspc rule -a discord desktop='^9'
bspc rule -a UnityHub desktop='^10'

# Colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# startup
autorandr -c
~/.config/polybar/launch.sh &
./.fehbg
picom --config /home/sisoro/.config/picom/picom.conf &
nm-applet
bluetoothctl power on

